### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by grayfall** [zwdzwd/transvar#22]
I've spotted an issue with the latest release on Python 3:

```
Traceback (most recent call last):
  File "/Users/ilia/.cenvs/envs/mutagenesis/bin/transvar", line 36, in <module>
    args.func(args)
  File "/Users/ilia/.cenvs/envs/mutagenesis/lib/python3.6/site-packages/transvar/anno.py", line 197, in main
    db = AnnoDB(args, config)
  File "/Users/ilia/.cenvs/envs/mutagenesis/lib/python3.6/site-packages/transvar/annodb.py", line 76, in __init__
    idmap = load(open(args.uniprot))
  File "/Users/ilia/.cenvs/envs/mutagenesis/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

The issue is clearly related to https://github.com/zwdzwd/transvar/issues/20
I'm making a pull-request with a hotfix.

**Comment by zwdzwd** [comment]
Thanks for the fix. I have merged your pull request.
